packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

allowBuilds:
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

catalog:
  "server-only": 0.0.1
  "@types/node": ^24.12.4
  typescript: ^5.9.3
  zod: 4.4.3

catalogs:
  orpc:
    "@orpc/server": 1.14.5
    "@orpc/client": 1.14.5
    "@orpc/tanstack-query": 1.14.5
